### PR TITLE
Fix for bad wifi

### PR DESCRIPTION
**Pull request by ciaranj**
I was hitting a problem where calendar events just 'stopped appearing'.  It turned out I was having internet connectivity issues at the router and the calendar scanning code was not handling it well. 

There's also some commits in here that allowed me to test/debug/work on the code without it running inside of MagicMirror, you may not want those changes ?

### CODE REVIEW

**Comment by eouia** [comment]
Is there any change in user experience?

**Comment by ciaranj** [comment]
Other than it will now recover after failure, no not really.

The converse is it will indefinitely retry an iCal feed that errors?

**Comment by eouia** [comment]
Thanks for your contribution.

**Comment by eouia** [comment]
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1

**Pull request merged**
