### PR TITLE
fixed duplication of modules because of race condition in work function;

### PR DESCRIPTION
**Pull request by Tom-Hirschberger**
fixed switching to default scene 0 not possible

### CODE REVIEW

**Comment by Tom-Hirschberger** [comment]
Needed to change some more things because the module might be hidden but the profile changes

**Comment by Tom-Hirschberger** [comment]
Mayby the flickering problem can be solved by adding an additional option to the changeScene functions which uses the "normal" behavior as default be makes it possible to suppress the additional resume call

**Comment by eouia** [comment]
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1

**Comment by Tom-Hirschberger** [comment]
Hi,I already read the sad news. Thank you for your great work. I don't want to promise things I can't keep. I'm currently studying Master of Computer Sience and don't have much time, too. I hope there is someone with more time and more knowledge about JavaScript than me but I will follow the thread in the forum. Am 10.05.2020 16:47 schrieb Seongnoh Sean Yi <notifications@github.com>:
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1

**Comment by eouia** [comment]
Thanks for replying.

**Pull request merged**
